### ISSUE TITLE
No model.h5

### ISSUE THREAD

**Issue by manesvenom** [Hironsan/BossSensor#5]
Hi, 

do I need to create the model.h5 manually during the training.

 python boss_train.py

OSError: Unable to create file (Unable to open file: name = './store/model.h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 602)
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x10e0a1e80>>
Traceback (most recent call last):

**Comment by manesvenom** [comment]
it needs to create a store folder.

**Comment by fortitude94deng** [comment]
hello ,bro ,how to do with it
